NotificacionesSIGET/Controllers/NotificacionesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using NotificacionesSIGET.Areas.Identity.Data;
using NotificacionesSIGET.Data;
using NotificacionesSIGET.Models;
using NotificacionesSIGET.Tools;
using NotificacionesSIGET.ViewModels;

namespace NotificacionesSIGET.Controllers
{
    public class NotificacionesController : Controller
    {
        private readonly ApplicationDbContext _context;
        //private readonly IHostingEnvironment _hostingEnvironment;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly IConfiguration _configuration;


        public NotificacionesController(ApplicationDbContext context,
          //                              IHostingEnvironment hostingEnvironment,
                                        RoleManager<IdentityRole> roleManager,
                                        UserManager<AppUser> userManager,
                                        IConfiguration configuration)
        {
            _context = context;
            //_hostingEnvironment = hostingEnvironment;
            _roleManager = roleManager;
            _userManager = userManager;
            _configuration = configuration;
        }

        [Authorize(Roles = "Notificador")]

        // GET: Notificaciones 
        public async Task<IActionResult> Index()
        {
            try
            {

                Herramientas.EscribirLog("Notificaciones-Index", "Se ingresa a Index del Notificaciones", "",
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);

                var applicationDbContext = _context.notificacion;

                var result = (from Notificacion in applicationDbContext
                              join u in _userManager.Users on Notificacion.PublicadoPor equals u.Id
                              select new Notificacion
                              {
                                  Id = Notificacion.Id,
                                  Comentario = Notificacion.Comentario,
                                  unidad = Notificacion.unidad,
                                  documento = Notificacion.documento,
                                  empresa = Notificacion.empresa,
                                  PublicadoPor = u.Nombres + " " + u.Apellidos,
                                  Fecha = Notificacion.Fecha,
                                  FechaDescarga = Notificacion.FechaDescarga,
                                  Notificado = Notificacion.Notificado
                              }).ToListAsync();

                return View(await result);
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        // GET: Notificaciones/Details/5 
        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                Herramientas.EscribirLog("Notificaciones-Details", "Se ingresa a Details del Notificaciones", id.ToString(),
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);
                if (id == null)
                {
                    return NotFound();
                }

                var notificacion = await _context.notificacion
                    .Include(n => n.documento)
                    .Include(n => n.empresa)
                    .Include(n => n.unidad)
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (notificacion == null)
                {
                    return NotFound();
                }
                return View(notificacion);
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        [Authorize(Roles = "Notificador")]

        // GET: Notificaciones/Create 
        public IActionResult Create()
        {
            try
            {
                Herramientas.EscribirLog("Notificaciones-Create", "Se ingresa a Create del Notificaciones", "",
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);

                ViewData["DocumentoId"] = new SelectList(_context.documentos, "id", "Nombre");
                ViewData["EmpresaId"] = new SelectList(_context.empresa, "Id", "Nombre");
                ViewData["UnidadId"] = new SelectList(_context.unidad, "Id", "Nombre");

                return View();
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }
        // GET: Notificaciones/Create 
        public IActionResult Creacion()
        {
            try
            {
                Herramientas.EscribirLog("Notificaciones-Create", "Se ingresa a Create del Notificaciones", "",
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);

                ViewData["DocumentoId"] = new SelectList(_context.documentos, "id", "Nombre");
                ViewData["EmpresaId"] = new SelectList(_context.empresa, "Id", "Nombre");
                ViewData["UnidadId"] = new SelectList(_context.unidad, "Id", "Nombre");

                return View();
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }
        // POST: Notificaciones/Create 
        // To protect from overposting attacks, enable the specific properties you want to bind to, for  
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598. 
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Notificador")]

        public async Task<IActionResult> Create([Bind("Id,Notificado,ComentarioNotificacion,UnidadId,DocumentoId,EmpresaId," +
            "Descripcion,Numero,Fecha,ListaEmpresas")] VMNotificado notificacion)
        {
            try
            {
                var usuarioId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                Herramientas.EscribirLog("Notificaciones-Create", "Se Creo una Notificaciones", notificacion.Id.ToString(),
                                                            usuarioId, _context);
                if (ModelState.IsValid)
                {
                    notificacion.FechaDocumento = _context.documentos
                        .Where(x => x.id == notificacion.DocumentoId).Select(x => x.Fecha).FirstOrDefault();

                    notificacion.Fecha = DateTime.Now;

                    notificacion.DocumentoNumero = _context.documentos
                        .Where(x => x.id == notificacion.DocumentoId).Select(x => x.Numero).FirstOrDefault();

                    notificacion.TipoDocumentoNombre = _context.documentos.Include(n => n.tipoDocumento).
                        Where(x => x.id == notificacion.DocumentoId).Select(x => x.tipoDocumento.nombre).FirstOrDefault();

                    foreach (var empresa in notificacion.ListaEmpresas)
                    {
                        notificacion.EmpresaId = Convert.ToInt16(empresa);

                        Notificacion Notificacion = new Notificacion
                        {
                            Notificado = 1,
                            Comentario = notificacion.ComentarioNotificacion,
                            UnidadId = Convert.ToInt16(notificacion.UnidadId),
                            DocumentoId = Convert.ToInt16(notificacion.DocumentoId),
                            EmpresaId = Convert.ToInt16(empresa),
                            Fecha = DateTime.Now,
                            PublicadoPor = usuarioId
                        };

                        _context.Add(Notificacion);
                        _context.SaveChanges();

                        EnviaMail(notificacion);
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        private void EnviaMail(VMNotificado notificacion)
        {
            var usuarioId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var hora = Herramientas.HoraALetras(notificacion.Fecha);
            var fechaNotificacion = Herramientas.FechaALetras(notificacion.Fecha);

            notificacion.EmpresaNombre = _context.empresa.Where(x => x.Id == notificacion.EmpresaId)
                                         .Select(x => x.Nombre).FirstOrDefault();

            EnviaMail mail = new EnviaMail();

            var cuerpo = $"<table><tr><th><h2>Superintendencia General de Electricidad y Telecomunicaciones</h2>" +
                $"</th></tr><tr><th><h3>Sistema de Notificaciones Electrónicas SIGET</h3></th></tr><tr><th align='left'>" +
                $"{notificacion.EmpresaNombre} :<br /><br />Por este medio notifico que en la Superintendencia " +
                $"General de Electricidad y Telecomunicaciones se ha emitido el acto administrativo " +

NotificacionesSIGET/Views/Notificaciones/Creacion.cshtml
@model VMNotificado

@{
    ViewData["Title"] = "Creacion de Notificacion";
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">@ViewBag.Title</h3>
            </div>
            <form asp-action="Create" enctype="multipart/form-data">
                <div class="card-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="input-group">
                        <div class="custom-file">
                            <input id="inputImagen" type="file" asp-for="FFArchivo" class="custom-file-input">
                            <label id="labelImagen" class="custom-file-label">Selecciona un archivo</label>
                            <span asp-validation-for="FFArchivo" class="text-danger"></span>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-lg">
                            <div class="form-group">
                                <label asp-for="Numero" class="control-label"></label>
                                <input asp-for="Numero" class="form-control" />
                                <span asp-validation-for="Numero" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg">
                            <div class="form-group">
                                <label asp-for="Fecha" class="control-label"></label>
                                <input asp-for="Fecha" class="form-control" />
                                <span asp-validation-for="Fecha" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Descripcion" class="control-label"></label>
                        <input asp-for="Descripcion" class="form-control" />
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UnidadId" class="control-label"></label>
                        <select asp-for="UnidadId" class="form-control" asp-items="ViewBag.UnidadId"></select>
                    </div>
                    <hr />
                    <div class="form-group">
                        <label asp-for="EmpresaId" class="control-label"></label>
                        <select class="form-control select2" multiple="multiple" asp-for="ListaEmpresas" 
                                asp-items="ViewBag.EmpresaId" style="width: 100%;" ></select>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-success btn-flat btn-block"><i class="fas fa-save"></i> Crear</button>
                        </div>
                        <div class="col-md-4">
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-default btn-flat btn-block" asp-action="Index"><i class="fas fa-chevron-left"></i> Regresar a lista</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.select2').select2()
        })
    </script>
}

NotificacionesSIGET/Views/Notificaciones/Create.cshtml
@model VMNotificado

@{
    ViewData["Title"] = "Creacion de Notificacion";
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">@ViewBag.Title</h3>
            </div>
            <form asp-action="Create" enctype="multipart/form-data">

                <div class="card-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="ComentarioNotificacion" class="control-label"></label>
                        <input asp-for="ComentarioNotificacion" class="form-control" />
                        <span asp-validation-for="ComentarioNotificacion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UnidadId" class="control-label"></label>
                        <select asp-for="UnidadId" class="form-control" asp-items="ViewBag.UnidadId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="DocumentoId" class="control-label"></label>
                        <select asp-for="DocumentoId" class="form-control" asp-items="ViewBag.DocumentoId"></select>
                    </div>
                    @*<div class="form-group">
                        <label asp-for="EmpresaId" class="control-label"></label>
                        <select asp-for="EmpresaId" class="form-control" asp-items="ViewBag.EmpresaId"></select>
                    </div>*@
                    <div class="form-group">
                        <label asp-for="EmpresaId" class="control-label"></label>
                        <select class="form-control select2" multiple="multiple" asp-for="ListaEmpresas"
                                asp-items="ViewBag.EmpresaId" style="width: 100%;"></select>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-success btn-flat btn-block"><i class="fas fa-save"></i> Crear</button>
                        </div>
                        <div class="col-md-4">
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-default btn-flat btn-block" asp-action="Index"><i class="fas fa-chevron-left"></i> Regresar a lista</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.select2').select2()
        })
    </script>
}

NotificacionesSIGET/Views/Notificaciones/Delete.cshtml
@model NotificacionesSIGET.Models.Notificacion

@{
    ViewData["Title"] = "Eliminar Notificacion";
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card card-danger">
            <div class="card-header">
                <h3 class="card-title">
                    ¿Esta seguro de eliminar este elemento?
                </h3>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Comentario)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Comentario)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.unidad)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.unidad.Nombre)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.documento)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.documento.Nombre)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.empresa)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.empresa.Nombre)
                    </dd>
                </dl>
            </div>
            <div class="card-footer">
                <form asp-action="Delete">
                    <div class="row">
                        <div class="col-md-4">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Eliminar" class="btn btn-danger btn-flat btn-block" />
                        </div>
                        <div class="col-md-3">
                        </div>
                        <div class="col-md-5">
                            <a class="btn btn-default btn-flat btn-block" asp-action="Index"><i class="fas fa-chevron-left"></i> Regresar a la lista</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

NotificacionesSIGET/Views/Notificaciones/Details.cshtml
@model NotificacionesSIGET.Models.Notificacion

@{
    ViewData["Title"] = "Detalle de Notificacion";
}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card card-secondary">
            <div class="card-header">
                <h3 class="card-title">
                    @ViewBag.Title
                </h3>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Comentario)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Comentario)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.unidad)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.unidad.Nombre)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.documento)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.documento.descripcion)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.empresa)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.empresa.Nombre)
                    </dd>
                </dl>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-md-4">
                        <a class="btn btn-warning btn-flat btn-block" asp-action="Edit" asp-route-id="@Model.Id"><i class="fas fa-edit"></i> Editar</a>
                    </div>
                    <div class="col-md-3">

                    </div>
                    <div class="col-md-5">
                        <a class="btn btn-default btn-flat btn-block" asp-action="Index"><i class="fas fa-chevron-left"></i> Regresar a la lista</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

NotificacionesSIGET/Views/Notificaciones/Detalle.cshtml
@model IEnumerable<Notificacion>

@{
    ViewData["Title"] = "Notificacion";
}


<div class="row">
    <div class="col-12">
        @if (ViewBag.Mensaje != null)
        {
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-check"></i> Exito!</h5>
                @ViewBag.Mensaje
            </div>
        }
        <div class="card">
            <div class="card-body table-responsive p-3">
                <table id="dataTable" class="table table-hover">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Comentario)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.documento)
                            </th>

                            <th>

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr @(item.Notificado != 1 ? String.Empty : "style=background-color:lightgreen")>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Comentario)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.documento.Nombre)
                                </td>
                                <td class="text-right">
                                    <a class="btn btn-primary" asp-action="DescargaArchivo" asp-route-id="@item.Id"><i class="fas fa-download"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script type="text/javascript">

        $(document).ready(function () {
            $("a").click(function () {

                setTimeout(function () {
                    location.reload();
                }, 1000);

            });
        });

        $(function () {
            $("#dataTable").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
        });

    </script>
}

NotificacionesSIGET/Views/Notificaciones/Index.cshtml
@model IEnumerable<NotificacionesSIGET.Models.Notificacion>

@{
    ViewData["Title"] = "Detalle de Notificaciones";
}

<p>
    <a class="btn btn-primary" asp-action="Create"><i class="fas fa-plus"></i> Crear Nuevo</a>
</p>
<div class="row">
    <div class="col-12">
        @if (ViewBag.Mensaje != null)
        {
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-check"></i> Exito!</h5>
            @ViewBag.Mensaje
        </div>
        }
        <div class="card">
            <div class="card-body table-responsive p-3">
                <table id="dataTable" class="table table-hover">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Comentario)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.unidad)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.documento)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.empresa)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PublicadoPor)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Fecha)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FechaDescarga)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr @(item.Notificado == 0 ? String.Empty : "style=background-color:lightgreen")>
                            <td>
                                @Html.DisplayFor(modelItem => item.Comentario)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.unidad.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.documento.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.empresa.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PublicadoPor)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Fecha)
                            </td>
                            <td>
                                @if(item.Notificado == 0){
                                @Html.DisplayFor(modelItem => item.FechaDescarga)
                                }
                            </td>
                            <td class="text-right">
                                @*<a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id" title="Editar"><i class="fas fa-edit"></i></a>
                                    <a class="btn btn-default" asp-action="Details" asp-route-id="@item.Id" title="Detalle"><i class="fas fa-eye"></i></a>*@
                                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id" title="Eliminar"><i class="fas fa-trash"></i></a>
                                <button class="btn btn-info" id="ReenviaMail" onclick="reenviar(@item.Id)"><i class="fas fa-envelope"></i></button>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $("#dataTable").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
        });

        function reenviar(id) {
            $.ajax({
                type: "GET",
                url: '@Url.Action("ReenviaMail","Notificaciones")',
                data: {id: id},
                contentType: "application/json",
                success: function (data) {
                    if (data) {
                        alert("Se realizo en reenvio del correo.");
                    }
                }
            });
        }
    </script>
}