NotificacionesSIGET/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NotificacionesSIGET.Data;
using NotificacionesSIGET.Models;
using Microsoft.AspNetCore.Authorization;
using NotificacionesSIGET.Tools;
using System.Security.Claims;

namespace NotificacionesSIGET.Controllers
{
    [Authorize(Roles = "Administrador, Notificador")]
    public class EmpresasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmpresasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Empresas
        public async Task<IActionResult> Index()
        {
            try
            {

                Herramientas.EscribirLog("Empresas-Index", "Se ingresa a Index del Empresas", "",
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);
                
                    var applicationDbContext = _context.empresa.Include(e => e.sector);
                    return View(await applicationDbContext.ToListAsync());
                
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex,_context);
                return View();
            }
        }

        // GET: Empresas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            try
            {

                Herramientas.EscribirLog("Empresas-Details", "Se ingresa a Details del Empresas", id.ToString(),
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);
                if (id == null)
            {
                return NotFound();
            }

            var empresa = await _context.empresa
                .Include(e => e.sector)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (empresa == null)
            {
                return NotFound();
            }

            return View(empresa);
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        // GET: Empresas/Create
        public IActionResult Create()
        {
            try
            {

                Herramientas.EscribirLog("Documento-Create", "Se ingresa a Create del Empresas", "",
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);

                ViewData["SectorId"] = new SelectList(_context.sector, "Id", "Nombre");
                return View();
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        // POST: Empresas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,SectorId,Representante")] Empresa empresa)
        {
            try
            {
                Herramientas.EscribirLog("Empresas-Create", "Se Crea la Empresa", empresa.Id.ToString(),
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);
                if (ModelState.IsValid)
                {
                    _context.Add(empresa);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["SectorId"] = new SelectList(_context.sector, "Id", "sector", empresa.sector);
                return View(empresa);
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        // GET: Empresas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {

                Herramientas.EscribirLog("Documento-Delete", "Se ingresa a Delete del Empresas", id.ToString(),
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);

                if (id == null)
                {
                    return NotFound();
                }

                var empresa = await _context.empresa.FindAsync(id);
                if (empresa == null)
                {
                    return NotFound();
                }
                ViewData["SectorId"] = new SelectList(_context.sector, "Id", "Nombre", empresa.sector);
                return View(empresa);
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        // POST: Empresas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,SectorId,Representante")] Empresa empresa)
        {
            try
            {

                Herramientas.EscribirLog("Documento-Edit", "Se ingresa a Edit del Empresas", id.ToString(),
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);
                if (id != empresa.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(empresa);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!EmpresaExists(empresa.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ViewData["SectorId"] = new SelectList(_context.sector, "Id", "sector", empresa.sector);
                return View(empresa);
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        // GET: Empresas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {

                Herramientas.EscribirLog("Documento-Delete", "Se ingresa a Delete del Empresas", id.ToString(),
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);
                if (id == null)
                {
                    return NotFound();
                }

                var empresa = await _context.empresa
                    .Include(e => e.sector)
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (empresa == null)
                {
                    return NotFound();
                }

                return View(empresa);
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        // POST: Empresas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {

                Herramientas.EscribirLog("Documento-DeleteConfirmed", "Se DeleteConfirmed del Empresas", id.ToString(),
                                                            User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);
                var empresa = await _context.empresa.FindAsync(id);
                _context.empresa.Remove(empresa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }

        }

        private bool EmpresaExists(int id)
        {
            return _context.empresa.Any(e => e.Id == id);
        }
    }
}

NotificacionesSIGET/Controllers/GruposController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NotificacionesSIGET.Data;
using NotificacionesSIGET.Models;

namespace NotificacionesSIGET.Controllers
{
    [Authorize]
    public class GruposController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GruposController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Grupos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Grupo.ToListAsync());
        }

        // GET: Grupos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grupo = await _context.Grupo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grupo == null)
            {
                return NotFound();
            }

            return View(grupo);
        }

        // GET: Grupos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Grupos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre")] Grupo grupo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(grupo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(grupo);
        }

        // GET: Grupos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grupo = await _context.Grupo.FindAsync(id);
            if (grupo == null)
            {
                return NotFound();
            }
            return View(grupo);
        }

        // POST: Grupos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre")] Grupo grupo)
        {
            if (id != grupo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grupo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GrupoExists(grupo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(grupo);
        }

        // GET: Grupos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grupo = await _context.Grupo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grupo == null)
            {
                return NotFound();
            }

            return View(grupo);
        }

        // POST: Grupos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grupo = await _context.Grupo.FindAsync(id);
            _context.Grupo.Remove(grupo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GrupoExists(int id)
        {
            return _context.Grupo.Any(e => e.Id == id);
        }
    }
}

NotificacionesSIGET/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NotificacionesSIGET.ViewModels;
using Microsoft.AspNetCore.Authorization;
using NotificacionesSIGET.Tools;
using System.Security.Claims;
using NotificacionesSIGET.Data;

namespace NotificacionesSIGET.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;


        public RolesController(RoleManager<IdentityRole> roleManager,
                                ApplicationDbContext context)
        {
            _roleManager = roleManager;
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            try
            {

                Herramientas.EscribirLog("Roles-Index", "Se ingresa a Index del Roles", "",
                                                    User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);

                return View(_roleManager.Roles);


            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        public IActionResult Create()
        {
            try
            {

                Herramientas.EscribirLog("Roles-Create", "Se ingresa a Create del Roles", "",
                                                    User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);
                return View();
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(string RolName)
        {
            try
            {

                Herramientas.EscribirLog("Roles-Create", "Se crea Rol", RolName,
                                                    User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);

                if (!string.IsNullOrEmpty(RolName))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(RolName));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(RolName);
        }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
    }
}

        public ActionResult Details(string id)
        {
            try
            {

                Herramientas.EscribirLog("Roles-Details", "Se ingresa a Details del Roles", id,
                                                    User.FindFirst(ClaimTypes.NameIdentifier).Value, _context);

                return View(_roleManager.Roles.FirstOrDefault(x => x.Id == id));
            }
            catch (Exception ex)
            {
                Herramientas.EscribirLog(ex, _context);
                return View();
            }
        }

    }
}

NotificacionesSIGET/Views/Shared/_Aside.cshtml
@inject SignInManager<AppUser> SignInManager
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="~/img/logo_goes.png"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span style="font-family:museoSans-700-Regular">SIGET</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/img/man.png" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="/Home/index" class="d-block">@User.Identity.Name</a>
            </div>
        </div>
        @if (SignInManager.IsSignedIn(User) )
        {
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <li class="nav-header">ACCIONES</li>
                    <!-- Empleados -->
                    @if (User.IsInRole("Notificador"))
                    {
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa fa-id-card"></i>
                                <p>
                                    Notificaciones
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Documentos" asp-action="Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Documentos</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Notificaciones" asp-action="Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Notificaciones</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa fa-id-card"></i>
                                <p>
                                    Administracion
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Empresas" asp-action="Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Empresas</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Usuarios" asp-action="Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Usuarios</p>
                                    </a>
                                </li>
                            </ul>

                        </li>

                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa fa-id-card"></i>
                                <p>
                                    Reporte
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Reportes" asp-action="Index" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Reporte</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        }
                        <!-- Administrador -->
                        @if (User.IsInRole("Administrador"))
                        {

                            <li class="nav-item has-treeview">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon far fa-list-alt"></i>
                                    <p>
                                        Administracion
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a asp-controller="Usuarios" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Usuarios</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Roles" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Roles</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Empresas" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Empresas</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Unidades" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Unidades</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Sectores" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Sectores</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Parametros" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Parametros</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="TipoDocumentos" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Tipo Documento</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="TipoPersonas" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Tipo Persona</p>
                                        </a>
                                    </li>
                                    @*<li class="nav-item">
                                        <a asp-controller="Grupos" asp-action="Index" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Grupos</p>
                                        </a>
                                    </li>*@
                                </ul>
                            </li>
                        }
                        <!-- usuario  -->
                        @if (User.IsInRole("Usuario"))
                        {

                            <li class="nav-item has-treeview">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon far fa-list-alt"></i>
                                    <p>
                                        Notificaciones
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a asp-controller="Notificaciones" asp-action="Detalle" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Notificaciones</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
            </nav>
            <!-- /.sidebar-menu -->
        }
    </div>
    <!-- /.sidebar -->
</aside>